### ISSUE TITLE
Error: Cannot open vue-nodegui-starter/node_modules/@nodegui/nodegui/build/Release/nodegui_core.node

### ISSUE THREAD

**Issue by rmlzy** [nodegui/vue-nodegui-starter#7]
I’m trying Nodegui for the first time. Here’s my machine configuration:

```
env: macOS Big Sur 11.3 Beta
node version: v14.15.1
npm version: 7.6.0
```

**Reproduction Step**

Step1: clone the repo: `git clone https://github.com/nodegui/vue-nodegui-starter`

Step2: install dependencies, `cd vue-nodegui-starter && npm install`

Step3: run `npm run dev`, i got below errors:
```
Error: Cannot open /Users/rmlzy/Documents/awesome/vue-nodegui-starter/node_modules/@nodegui/nodegui/build/Release/nodegui_core.node: Error: dlopen(/Users/rmlzy/Documents/awesome/vue-nodegui-starter/node_modules/@nodegui/nodegui/build/Release/nodegui_core.node, 1): no suitable image found.  Did find:
	/Users/rmlzy/Documents/awesome/vue-nodegui-starter/node_modules/@nodegui/nodegui/build/Release/nodegui_core.node: mach-o, but wrong architecture
	/Users/rmlzy/Documents/awesome/vue-nodegui-starter/node_modules/@nodegui/nodegui/build/Release/nodegui_core.node: mach-o, but wrong architecture
    at Object.<anonymous> (/Users/rmlzy/Documents/awesome/vue-nodegui-starter/dist/main.js:1:214340)
    at Object.<anonymous> (/Users/rmlzy/Documents/awesome/vue-nodegui-starter/dist/main.js:1:214485)
    at n (/Users/rmlzy/Documents/awesome/vue-nodegui-starter/dist/main.js:1:110)
    at Object.<anonymous> (/Users/rmlzy/Documents/awesome/vue-nodegui-starter/dist/main.js:1:1007)
    at n (/Users/rmlzy/Documents/awesome/vue-nodegui-starter/dist/main.js:1:110)
    at Object.<anonymous> (/Users/rmlzy/Documents/awesome/vue-nodegui-starter/dist/main.js:1:1275)
    at n (/Users/rmlzy/Documents/awesome/vue-nodegui-starter/dist/main.js:1:110)
    at Object.<anonymous> (/Users/rmlzy/Documents/awesome/vue-nodegui-starter/dist/main.js:1:213894)
    at n (/Users/rmlzy/Documents/awesome/vue-nodegui-starter/dist/main.js:1:110)
    at Object.<anonymous> (/Users/rmlzy/Documents/awesome/vue-nodegui-starter/dist/main.js:1:7160)
```

Can someone help me, please.

**Comment by rmlzy** [comment]
close for no response.
