### ISSUE TITLE
Packaged AppImage errors

### ISSUE THREAD

**Issue by jswhisperer** [nodegui/vue-nodegui-starter#8]
<details>
  <summary>npm i output!</summary>
  
  <code>
[ 99%] Building CXX object CMakeFiles/nodegui_core.dir/src/cpp/lib/QtWidgets/QStandardItem/qstandarditem_wrap.cpp.o
[100%] Linking CXX shared library Release/nodegui_core.node
[100%] Built target nodegui_core
npm WARN vue-nodegui-starter@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 678 packages from 479 contributors and audited 683 packages in 544.363s

16 packages are looking for funding
  run `npm fund` for details

found 10 vulnerabilities (4 low, 3 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details
gnb@gnb-MacBookPro:~/Desktop/vue-nodegui-starter-master$ 

</code>
</details>

<details>
  <summary> npm run build "webpack -p"</summary>
  <code>
gnb@gnb-MacBookPro:~/Desktop/vue-nodegui-starter-master$ npm i --save-dev @nodegui/packer

> @nodegui/packer@1.4.1 postinstall /home/gnb/Desktop/vue-nodegui-starter-master/node_modules/@nodegui/packer
> node ./scripts/setupBinaries.js

Downloading Linux deploy Qt [=============================] 100% of 13.98MB 0.0s
Setting up permissions for linuxdeployqt
npm WARN @vue/compiler-sfc@3.0.1 requires a peer of vue@3.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN vue-nodegui-starter@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ @nodegui/packer@1.4.1
added 7 packages from 17 contributors and audited 690 packages in 20.759s

17 packages are looking for funding
  run `npm fund` for details

found 10 vulnerabilities (4 low, 3 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details
gnb@gnb-MacBookPro:~/Desktop/vue-nodegui-starter-master$ npm runbuild

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, fund, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    /home/gnb/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.14.10 /home/gnb/.nvm/versions/node/v14.15.4/lib/node_modules/npm

Did you mean this?
    rebuild
gnb@gnb-MacBookPro:~/Desktop/vue-nodegui-starter-master$ npm run build

> vue-nodegui-starter@1.0.0 build /home/gnb/Desktop/vue-nodegui-starter-master
> webpack -p

Hash: cfa8d6ef691b03afcc7a
Version: webpack 4.44.2
Time: 29273ms
Built at: 2021-04-28 12:08:07 p.m.
                                Asset      Size  Chunks             Chunk Names
00340d44a949fea32e5c523f38d68436.node  7.79 MiB          [emitted]  
                              main.js  3.09 MiB       0  [emitted]  main
Entrypoint main = main.js
 [22] external "path" 42 bytes {0} [built]
 [30] external "os" 42 bytes {0} [built]
 [43] (webpack)/buildin/module.js 497 bytes {0} [built]
 [81] external "url" 42 bytes {0} [built]
 [82] ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js + 2 modules 313 KiB {0} [built]
      |    3 modules
[180] external "events" 42 bytes {0} [built]
[211] external "fs" 42 bytes {0} [built]
[221] external "crypto" 42 bytes {0} [built]
[291] external "http" 42 bytes {0} [built]
[292] external "https" 42 bytes {0} [built]
[293] external "querystring" 42 bytes {0} [built]
[294] external "zlib" 42 bytes {0} [built]
[314] ./main.js + 10 modules 3.95 KiB {0} [built]
      | ./main.js 104 bytes [built]
      | ./App.vue 291 bytes [built]
      | ./App.vue?vue&type=template&id=c0b6c0d8&bindings={"inc":"setup","count":"setup","counterStyle":"setup"} 238 bytes [built]
      | ./App.vue?vue&type=script&lang=js 210 bytes [built]
      | ./node_modules/vue-loader/dist/templateLoader.js??ref--5!./node_modules/vue-loader/dist??ref--0!./App.vue?vue&type=template&id=c0b6c0d8&bindings={"inc":"setup","count":"setup","counterStyle":"setup"} 793 bytes [built]
      | ./node_modules/vue-loader/dist??ref--0!./App.vue?vue&type=script&lang=js 417 bytes [built]
      | ./Hero.vue 253 bytes [built]
      | ./Hero.vue?vue&type=template&id=634e7e68&bindings={"viewStyle":"setup"} 198 bytes [built]
      | ./Hero.vue?vue&type=script&lang=js 212 bytes [built]
      | ./node_modules/vue-loader/dist/templateLoader.js??ref--5!./node_modules/vue-loader/dist??ref--0!./Hero.vue?vue&type=template&id=634e7e68&bindings={"viewStyle":"setup"} 753 bytes [built]
      | ./node_modules/vue-loader/dist??ref--0!./Hero.vue?vue&type=script&lang=js 567 bytes [built]
    + 302 hidden modules
gnb@gnb-MacBookPro:~/Desktop/vue-nodegui-starter-master$ npm run build

> vue-nodegui-starter@1.0.0 build /home/gnb/Desktop/vue-nodegui-starter-master
> webpack -p

Hash: cfa8d6ef691b03afcc7a
Version: webpack 4.44.2
Time: 11279ms
Built at: 2021-04-28 12:10:40 p.m.
                                Asset      Size  Chunks             Chunk Names
00340d44a949fea32e5c523f38d68436.node  7.79 MiB          [emitted]  
                              main.js  3.09 MiB       0  [emitted]  main
Entrypoint main = main.js
 [22] external "path" 42 bytes {0} [built]
 [30] external "os" 42 bytes {0} [built]
 [43] (webpack)/buildin/module.js 497 bytes {0} [built]
 [81] external "url" 42 bytes {0} [built]
 [82] ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js + 2 modules 313 KiB {0} [built]
      |    3 modules
[180] external "events" 42 bytes {0} [built]
[211] external "fs" 42 bytes {0} [built]
[221] external "crypto" 42 bytes {0} [built]
[291] external "http" 42 bytes {0} [built]
[292] external "https" 42 bytes {0} [built]
[293] external "querystring" 42 bytes {0} [built]
[294] external "zlib" 42 bytes {0} [built]
[314] ./main.js + 10 modules 3.95 KiB {0} [built]
      | ./main.js 104 bytes [built]
      | ./App.vue 291 bytes [built]
      | ./App.vue?vue&type=template&id=c0b6c0d8&bindings={"inc":"setup","count":"setup","counterStyle":"setup"} 238 bytes [built]
      | ./App.vue?vue&type=script&lang=js 210 bytes [built]
      | ./node_modules/vue-loader/dist/templateLoader.js??ref--5!./node_modules/vue-loader/dist??ref--0!./App.vue?vue&type=template&id=c0b6c0d8&bindings={"inc":"setup","count":"setup","counterStyle":"setup"} 793 bytes [built]
      | ./node_modules/vue-loader/dist??ref--0!./App.vue?vue&type=script&lang=js 417 bytes [built]
      | ./Hero.vue 253 bytes [built]
      | ./Hero.vue?vue&type=template&id=634e7e68&bindings={"viewStyle":"setup"} 198 bytes [built]
      | ./Hero.vue?vue&type=script&lang=js 212 bytes [built]
      | ./node_modules/vue-loader/dist/templateLoader.js??ref--5!./node_modules/vue-loader/dist??ref--0!./Hero.vue?vue&type=template&id=634e7e68&bindings={"viewStyle":"setup"} 753 bytes [built]
      | ./node_modules/vue-loader/dist??ref--0!./Hero.vue?vue&type=script&lang=js 567 bytes [built]
    + 302 hidden modules
gnb@gnb-MacBookPro:~/Desktop/vue-nodegui-starter-master$ 

</code>
</details>

npm run init ""init": "nodegui-packer --init MyAppName","

<details>
  <summary> "pack": "nodegui-packer --pack ./dist"</summary>
  <code>
internal/modules/cjs/loader.js:1023
  throw err;
  ^

Error: Cannot find module './dist'
Require stack:
- /tmp/.mount_ApplicdglQPA/index.js
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/tmp/.mount_ApplicdglQPA/index.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/tmp/.mount_ApplicdglQPA/index.js', 'internal/preload' ]
}
gnb@gnb-MacBookPro:~/Desktop/vue-nodegui-starter-master$ 
</code>
</details>

a

<details>
  <summary>and finally launching the app image </summary>
  <code>

internal/modules/cjs/loader.js:1023
  throw err;
  ^

Error: Cannot find module './dist'
Require stack:
- /tmp/.mount_ApplicdglQPA/index.js
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/tmp/.mount_ApplicdglQPA/index.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/tmp/.mount_ApplicdglQPA/index.js', 'internal/preload' ]
}
gnb@gnb-MacBookPro:~/Desktop/vue-nodegui-starter-master$ 

</code>
</details>

**Comment by MonsieurV** [comment]
I found that it works by changing `deploy/linux/<YourApp>/index.js` last line, from:

```js
require("./dist");
```

to 

```js
require("./dist/main.js");
```

(You need to require and call the actual Webpack bundle/target file)
