### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by savire** [nodegui/vue-nodegui-starter#9]
Not working on Windows 10

```
Minimal Qt 5.14.1 setup:
D:\New\NodeQT\vue-nodegui-starter\node_modules\progress\lib\node-progress.js:160
  complete = Array(Math.max(0, completeLength + 1)).join(this.chars.complete);
             ^

RangeError: Invalid array length
    at ProgressBar.render (D:\New\NodeQT\vue-nodegui-starter\node_modules\progress\lib\node-progress.js:160:14)
    at ProgressBar.tick (D:\New\NodeQT\vue-nodegui-starter\node_modules\progress\lib\node-progress.js:97:8)
    at PassThrough.<anonymous> (D:\New\NodeQT\vue-nodegui-starter\node_modules\@nodegui\artifact-installer\dist\downloader.js:54:49)
    at PassThrough.emit (events.js:322:22)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at PassThrough.Readable.push (_stream_readable.js:209:10)
    at PassThrough.Transform.push (_stream_transform.js:152:32)
    at PassThrough.afterTransform (_stream_transform.js:96:10)
    at PassThrough._transform (_stream_passthrough.js:46:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodegui/nodegui@0.25.0 setupqt: `cross-env node ./scripts/setupMiniQt.js`
npm ERR! Exit status 1
```

Dev Env settings:

```
PS D:\New\NodeQT\vue-nodegui-starter> npm --version
6.14.4
PS D:\New\NodeQT\vue-nodegui-starter> node --version
v12.16.3
PS C:\Program Files (x86)\Microsoft Visual Studio\Installer> .\vswhere.exe -property catalog_productDisplayVersion
16.8.3
```

**Comment by xandyxor** [comment]
me too
